// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Agent struct {
	Token string `json:"token"`
}

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID       string  `json:"id"`
	Username string  `json:"username"`
	Email    *string `json:"email,omitempty"`
}
